### PR TITLE
Rename getBalance.ts to eth/getBalance.ts

### PR DESCRIPTION
**Pull request by Pandapip1**
## Rationale

To avoid potential collisions, I recommend that file names of tests be equal to RPC endpoint names.

### CODE REVIEW

**Comment by SamWilsn** [comment]
I think you'll also need to update here:

https://github.com/wallet-test-framework/framework/blob/3ca993d3e175e8ddcdd3b8e7234d3d267ce38483/client/src/tests.ts#L20

**Comment by Pandapip1** [comment]
@SamWilsn re-requesting review

**Comment by SamWilsn** [comment]
We're deliberating between using directories (`eth/getBalance`) and underscores (`eth_getBalance`.)

**Comment by Pandapip1** [comment]
I would actually prefer directories. That's a good idea; I'll use that instead.

**Pull request merged**
